url: 'http://localhost:8888/getstatus?a=0&'
nodes:
  - name: "mu00"
    place: [2, 3]
  - name: "cpu01"
    place: [4, 8]
  - name: "cpu02"
    place: [9, 10]
  - name: "gpu00"
    place: [11, 12]
  - name: "gpu01"
    place: [13, 14]
  - name: "gpu02"
    place: [15, 16]
  - name: "gpu03"
    place: [17, 18]